# Generated by Django 4.1 on 2022-09-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(max_length=20)),
                ('risk_name', models.CharField(max_length=50)),
                ('risk_description', models.CharField(max_length=200)),
                ('risk_level', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
    ]
